application: tsmith14-pinboard
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /pic
  static_dir: pic
  
- url: /.*
  script: Main.app


libraries:
- name: jinja2
  version: latest